const constants = {

  INITIAL_FORM_STATE: "INITIAL_FORM_STATE",
  LOAD_FIELDS_SUCCESS: "LOAD_FIELDS_SUCCESS",
  SAVE_FIELDS_SUCCESS: "SAVE_FIELDS_SUCCESS",

  UPDATE_FORM_BUSY: "UPDATE_FORM_BUSY",

  AJAX_CALL_BEGIN: "AJAX_CALL_BEGIN",
  AJAX_CALL_ERROR: "AJAX_CALL_ERROR",
  AJAX_CALL_SUCCESS: "AJAX_CALL_SUCCESS",

  EDIT_GRAPH : "EDIT_GRAPH"
};

export default constants;
