const constants = {

  INITIAL_FORM_STATE: "INITIAL_FORM_STATE",

  AUTHENTICATION_LOGIN_REQUEST: "AUTHENTICATION_LOGIN_REQUEST",
  AUTHENTICATION_LOGIN_SUCCESS: "AUTHENTICATION_LOGIN_SUCCESS",
  AUTHENTICATION_LOGIN_ERROR: "AUTHENTICATION_LOGIN_ERROR",
  AUTHENTICATION_LOGOUT: "AUTHENTICATION_LOGOUT",

  LOAD_FIELDS_SUCCESS: "LOAD_FIELDS_SUCCESS",
  SAVE_FIELDS_SUCCESS: "SAVE_FIELDS_SUCCESS",

  UPDATE_FORM_BUSY: "UPDATE_FORM_BUSY",

  AJAX_CALL_BEGIN: "AJAX_CALL_BEGIN",
  AJAX_CALL_ERROR: "AJAX_CALL_ERROR",
  AJAX_CALL_SUCCESS: "AJAX_CALL_SUCCESS",

  MESSAGE_ADD: "MESSAGES_ADD",
  MESSAGE_CLEAR: "MESSAGE_CLEAR",
  MESSAGES_CLEAR: "MESSAGES_CLEAR",

  EDIT_GRAPH : "EDIT_GRAPH"
};

export default constants;
